---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: senhasegura
spec:
  provider:
    senhasegura:
      url: "https://senhasegura.changeme.com"
      module: DSM # Select senhasegura DSM module to sync secrets
      auth:
        clientId: "CHANGEME"
        clientSecretSecretRef:
          name: senhasegura-dsm-auth
          key: CLIENT_SECRET
      ignoreSslCertificate: false # Optional
      privateKeySecretRef: # Optional, used only when sensitive data has been encrypted in senhasegura
        key: PRIVATE_KEY
        name: senhasegura-dsm-auth
